Components with add item (+) button clear cached values when item is added
FarmData2/FarmData2 pull request #300
Opened 2024-06-06 16:07 UTC by Shahir-47

**Pull Request Description**

Fixes the following components:

- `components/CropSelector`
- `components/LocationSelector`
- `components/TraySizeSelector`
- `components/EquipmentSelector`

Additionally, adds or modifies the component tests to confirm that clicking the `+` clears the cached items. 

Closes #103
---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2024-06-06 18:23 UTC, Shahir-47 commented
Remove all the content tests for LocationSelector

2024-06-07 12:56 UTC, braughtg commented
When loading the Direct Seeding or the Transplanting pages I am seeing the following error reported in the console:

```
Uncaught (in promise) Error: Permission [object Object] does not exist.
    po http://farmos/sites/all/modules/farmdata2/uiUtil/uiUtil.js:2
    Tn http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    b http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    run http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:9
    update http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    se http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    he http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    X http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
    R http://farmos/sites/all/modules/farmdata2/_plugin-vue_export-helper/_plugin-vue_export-helper.js:13
uiUtil.js:2:65868
```

The cause of this error should be identified and resolved.

Note that the error does not occur when loading the Tray Seeding page, so comparison to the parts that deal with permissions may be one way to resolve this issue.  One immediate thought is that it may be due to some component that appears on the the Direct Seeding and Transplanting forms that does not appear on the Direct Seeding page.  So possibly the Equipment Selector?

2024-06-07 14:37 UTC, Shahir-47 commented on components/SelectorBase/SelectorBase.content.comp.cy.js
> +        cy.get('[data-cy="selector-add-button"]').click();
No .click() needed

2024-06-07 14:37 UTC, Shahir-47 commented on components/SelectorBase/SelectorBase.content.comp.cy.js
> +    const addClickedSpy = cy.spy().as('addClickedSpy');
remove the addClickedSpy

2024-06-07 14:37 UTC, Shahir-47 commented on components/CropSelector/CropSelector.permissions.comp.cy.js
> +        // Simulate a click on the add button and check if the event is emitted
get rid of the comment

2024-06-07 14:37 UTC, Shahir-47 commented on components/CropSelector/CropSelector.permissions.comp.cy.js
> +    const addClickedSpy = cy.spy().as('addClickedSpy');
get rid of the spy

2024-06-07 14:37 UTC, Shahir-47 commented on components/CropSelector/CropSelector.permissions.comp.cy.js
>    it('Admin can add crops and url is correct', () => {
change description

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.vue
>        v-bind:showValidityStyling="showValidityStyling"
Remove addLocationURL

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.vue
> +
remove blank line

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.permissions.comp.cy.js
>          cy.get('[data-cy="location-selector"]').should('exist');
check if the button exists

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.permissions.comp.cy.js
>        .should('have.been.calledOnce')
change the it description

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.addGreenhousesWithBedsContent.comp.cy.js
> +describe('Test the default LocationSelector content', () => {
change the description

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.addGreenhousesContent.comp.cy.js
> +describe('Test the default LocationSelector content', () => {
update description

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.addGreenhousesBehavior.comp.cy.js
> +describe('Test the LocationSelector component behavior', () => {
change the description

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.addGreenhousesBehavior.comp.cy.js
> +  it('Clicking add greenhouses button goes to the add location form and clears the greenhouses cache', () => {
change it comment

2024-06-07 14:37 UTC, Shahir-47 commented on components/LocationSelector/LocationSelector.addFieldsContent.comp.cy.js
> +        cy.wait('@urlIntercept').its('response.statusCode').should('eq', 200);
take out the click and check for buttons existence. Put these tests back into the .content file

2024-06-07 14:37 UTC, Shahir-47 commented on components/TraySizeSelector/TraySizeSelector.adminPermissions.comp.cy.js
> +        cy.get('[data-cy="selector-add-button"]').click();
don't click. put them back into the same permission file

2024-06-07 16:08 UTC, braughtg requested changes

2024-06-07 16:08 UTC, braughtg commented on components/SelectorBase/SelectorBase.content.comp.cy.js
> +        cy.get('[data-cy="selector-add-button"]');
Remove this line, which does not make an assertion.

2024-06-07 16:16 UTC, braughtg commented
> When loading the Direct Seeding or the Transplanting pages I am seeing the following error reported in the console:

This seems to have been a transitory issue that has resolved.

2024-06-07 16:32 UTC, merged