Builds the `WinterKill` component
FarmData2/FarmData2 pull request #314
Opened 2024-06-13 18:03 UTC by Shahir-47

**Pull Request Description**

Creates a component for indicating if a Cover Crop Seeding will be winter killed. Additionally, it creates an example page in `farm_fd2_examples` for the component and a set of component tests for the component.

Closes #311 
---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2024-06-17 17:25 UTC, braughtg commented
Flip this to a full PR when you are ready for me to have a look at it.

2024-06-17 18:24 UTC, Shahir-47 commented
> Flip this to a full PR when you are ready for me to have a look at it.

Ready for review!

2024-06-17 18:48 UTC, braughtg requested changes
The functionality here looks pretty good. A few small things in the code and:
- Can we reduce the space between the label and the checkbox?
- Can we reduce the space between the checkbox and the date input?

Hopefully enough that the calendar component appears reliably in mobile mode for iPhone SE.

With those things touched up, it will just need to have the tests implemented.

2024-06-17 18:48 UTC, braughtg commented on modules/farm_fd2_examples/src/entrypoints/winter_kill/App.vue
> +      The WinterKill component allows the user to specify if a crop seeding will
Change to "... if a crop will be winter killed."  (drop "seeding")

2024-06-17 18:48 UTC, braughtg commented on modules/farm_fd2_examples/src/module/farm_fd2_examples.links.menu.yml
> +  description: 'Example of the use of the WinterKIll Component.'
`I` should be `i` in `WinterKill` here.

2024-06-17 18:48 UTC, braughtg commented on components/WinterKill/WinterKill.vue
> + * winter-kill-date-group              | The `div` component containing the date input fields when the checkbox is selected.
I'm not quite sure what this div contains from this comment.  Is it just the one date field? If so use `field` here not `fields`.  Or is there more in here than the date field? If so, try to be more specific.

2024-06-17 19:03 UTC, Shahir-47 commented
> The functionality here looks pretty good. A few small things in the code and:
> 
> * Can we reduce the space between the label and the checkbox?
> * Can we reduce the space between the checkbox and the date input?
> 
> Hopefully enough that the calendar component appears reliably in mobile mode for iPhone SE.
> 
> With those things touched up, it will just need to have the tests implemented.

I can't change the space between the label and the checkbox as that is the default padding that comes with the label and the input column to the right of the label. If you remember last week, we couldn't change `<div class="col">` and `<label class="col-auto col-form-label col-form-label text-end" id="__BVID__474873___BV__BV_label___" for="winter-kill-checkbox">` because that is generated by `<BFormGroup>` and it overwrites whatever style  applied to `<div class="col">` and `<label class="col-auto col-form-label col-form-label text-end" id="__BVID__474873___BV__BV_label___" for="winter-kill-checkbox">`

 You can see the padding for the input col here:

![image](https://github.com/FarmData2/FarmData2/assets/98346408/6eed2170-02ec-40fc-8df3-dec74707ffa3)

 You can see the padding for the label here:

![image](https://github.com/FarmData2/FarmData2/assets/98346408/bcfe67c8-0c4d-4b32-afc7-365f8c30b2ca)


However, I can change the spacing between the checkbox and the date input.

2024-06-17 19:15 UTC, braughtg commented
However, I can change the spacing between the checkbox and the date input.

Sounds good. Try to shrink that down and see how we do with the calendar that pops up.

2024-06-17 19:20 UTC, Shahir-47 commented
> However, I can change the spacing between the checkbox and the date input. Sounds good. Try to shrink that down and see how we do with the calendar that pops up.

It does show on the iPhone SE if I double-click. Here's the mobile view with the spacing reduced: 

![image](https://github.com/FarmData2/FarmData2/assets/98346408/91f74c4e-c2fb-4fec-83f6-d810ccffc068)

Desktop view: 

![image](https://github.com/FarmData2/FarmData2/assets/98346408/301032ae-c81b-4e71-bbda-56d52e1638b2)

2024-06-17 19:22 UTC, Shahir-47 commented
Another related issue I encountered: When I tried to commit my changes the first time, winter_kill.exists.e2e.cy.js  always failed. However, when I run winter_kill.exists.e2e.cy.js and then commit it, the test passes, and the changes are committed with no issues.

2024-06-17 23:49 UTC, braughtg commented
> It does show on the iPhone SE if I double-click. 

It was showing for me about 50% of the time when I double clicked.  This may be resolved when actually running on mobile.  It sounds like the Bootstrap Vue Next uses the native date component when running on the device. When I get back we can try to launch this on a site we can access via mobile and check it out.

> Here's the mobile view with the spacing reduced:

Looks better! Nice work.

2024-06-17 23:51 UTC, braughtg commented
> Another related issue I encountered: When I tried to commit my changes the first time, winter_kill.exists.e2e.cy.js always failed. However, when I run winter_kill.exists.e2e.cy.js and then commit it, the test passes, and the changes are committed with no issues.

Strange behavior.  I'm not sure what was going on here without seeing the actual runs or some output showing how / why the test failed.  If it persists, please open an issue for it with as much detail as you can gather about the test failure.

2024-06-19 15:12 UTC, braughtg requested changes
Looking good! Just one comment on `WinterKill.vue` regarding JSDoc for events.

2024-06-19 15:12 UTC, braughtg commented on components/WinterKill/WinterKill.vue
One of the `emits` for each event should be commented to describe the event and its payload (if it has one).  For example, this is what the `EquipmentSelector` does for the `valid` event:
```Javascript
    isValid() {
      /**
       * The validity of the selected equipment changed.
       * @property {boolean} event whether the selected equipment is valid or not.
       */
      this.$emit('valid', this.isValid);
    },
```

If an event is emitted from multiple places, only one needs to have the JSDoc comment.

2024-06-21 13:30 UTC, merged