Add multi crop selector entry point
FarmData2/FarmData2 pull request #315
Opened 2024-06-17 13:33 UTC by sidlamsal

**Pull Request Description**

Adds:
- multi crop selector component
- component tests
- example page

closes #312 

---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2024-06-17 13:34 UTC, sidlamsal commented
Still working on making the component look exactly like the drawn example.

2024-06-17 17:24 UTC, braughtg commented
> Still working on making the component look exactly like the drawn example.

The drawn example was a good guess, but if you have alternatives you'd like to discuss, post them in a comment on the issue.  Otherwise, I'll look for you to flip this to a full PR and then I'll have a look at it.

2024-06-18 00:22 UTC, braughtg requested changes
I only had time for a quick review of this so far.  A few things that I noticed:

- The crop selector drop down should expand to fill the available area to its right.  See the `SelectorBase` example or the way the `EquipmentSelector` behaves in the `SoilDisturbance` example.
- The `+` should use a popup.  But I think this will largely take care of itself when #305 is merged. May just need a few prop changes.

2024-06-18 00:22 UTC, braughtg commented on components/MultiCropSelector/MultiCropSelector.vue
> +      selectedCrop: this.selected,
This should probably be `selectedCrops` to make it clear there can be multiple.

2024-06-18 00:22 UTC, braughtg commented on components/MultiCropSelector/MultiCropSelector.adminPermissions.comp.cy.js
> +import MultiCropSelector from '@comps/MultiCropSelector/MultiCropSelector.vue';
Do we actually have to click the `+` button here, or is it enough to just check that the `+` button is visible?  If so, then this test and the `guestPermissions` tests can be combined into one test file.

The `behavior` test will be the one that has to click the button and ensure that it goes to the correct page (or eventually that the correct page is loaded into the popup).

2024-06-19 16:50 UTC, braughtg requested changes
One small change here.  Then I'd like to do a full in person review tomorrow or Friday.

2024-06-19 16:50 UTC, braughtg commented on modules/farm_fd2_examples/src/module/farm_fd2_examples.links.menu.yml
> +  title: 'MultiCropSelector Example'
Change title to be just `MultiCropSelector` here so that the word "Example" does not appear in the menu.

2024-06-21 14:53 UTC, merged