Changes required indicator and delete button behavior for EquipmentSelector and MultiCropSelector
FarmData2/FarmData2 pull request #338
Opened 2024-06-29 01:22 UTC by sidlamsal

**Pull Request Description**

Adds the `includeDeleteButton` prop to `SelectorBase` to handle including both a delete button and the required `*`. 

Updates `MultiCropSelector` and `EquipmentSelector` so that when multiple items are selected, only the top item has `*` and all items have the delete button. With only one selected item, the top item has `*` but no delete button.

Additional testing for the 3 components have been added as well as an updated `SelectorBase` example page. 

closes #320 #319 

---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2024-06-29 13:44 UTC, braughtg requested changes
This looks pretty good.  

I find the interaction between the `includeDeleteButton` and `required` properties of `SelectorBase` in this PR to be a little confusing.

The way the `SelectorBase` worked before this PR is that the delete button appears when the `SelectorBase` is not required and something is selected.  Otherwise the delete button does not appear.

So it seems like, just changing the `isRequired` function in `MultiCropSelector` and `EquipmentSelector` (as you have done) so that only the first element is required would be sufficient.

If so then the`SelectorBase` component would not need to be changed at all.  The changes to `EqupimentSelector` and `MultiCropSelector` would be just to the `isRequired` method (because the `includeDeleteButton` prop goes away).

Do you think that will work?

2024-06-29 14:05 UTC, sidlamsal commented
> Do you think that will work?

The reason I added the new prop is because `required` was used in the `v-if` of the delete button and the indicator. As per the issue #320, when a second crop is added, the first crop should have the indicator and a delete button. I could not find a way to make this happen as even if only the first crop is required, it would not have a delete button when another crop is selected. My original changes were actually a little smaller, `addDeleteButton` had a default value of `!this.required` so it was less changes. However this caused an issue when running the exists e2e test for the multi crop example page when it would try to read the value `this.required` and would throw the error `Cannot read properties of undefined (reading 'required')`. We could just remove the `!required` from the `v-if` for the delete button, but I wasn't sure if that would be the desired behavior, so I tried to implement the new behavior with minimal changes to old behavior.

2024-06-29 14:23 UTC, braughtg commented
> We could just remove the `!required` from the `v-if` for the delete button

I think this is a good idea... maybe make the first one required only when there is 0 or 1 crop/equipment selected.  So once a second crop or equipment is selected then none of them are required (i.e. any of them can be deleted).  But once we get down to 1 crop or equipment selected then it will be required again.  Seems like that should be doable without changes to the `SelectorBase`.

2024-06-30 12:30 UTC, braughtg commented
Nicely done! I like this fix!

2024-06-30 12:33 UTC, merged