Refactor PicklistBase to Use Map for Selected Rows and Fix Sorting Issues
FarmData2/FarmData2 pull request #385
Opened 2024-09-30 21:22 UTC by Shahir-47

**Pull Request Description**

This PR refactors the `PicklistBase.vue` component to store selected rows in a `Map`, resolving the sorting-related issues described in #383. The internal `pickedRows` array is kept for `BFormSelect` compatibility, while the external `picked` prop now uses a `Map` for cleaner selection handling. Updates include:
- `PicklistBase.vue` refactor
- Changes to `TransplantingPicklist.vue`
- Updates to example pages and associated tests
- Modifications to end-to-end transplanting tests

Closes #383 

---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2024-10-02 13:44 UTC, braughtg commented on components/PicklistBase/PicklistBase.vue
> +                quantity: this.pickedRows[i],
Let's change this property to be `picked`.  The `row` already contains an entry for `quantity`

2024-10-02 14:03 UTC, braughtg requested changes
Overall really nice work!  

Just a few small changes and it should be ready to go.

2024-10-02 14:03 UTC, braughtg commented on components/PicklistBase/PicklistBase.vue
> +     * The keys of the Map are the original row indices from the `rows` array.
`The keys of the Map are row indices from the `rows` array.`

I don't think `original` matters here since the `rows` array is not actually changed.

2024-10-02 14:03 UTC, braughtg commented on components/PicklistBase/PicklistBase.vue
> +     * If the row is picked, the corresponding entry in the Map will have a `quantity` greater than 0.
If the row is picked, the Map will have an entry with the row number as the key and the value will have a `quantity` attribute containing a `1` if the `units` prop is not set, or the value picked if the `units` prop is set.

2024-10-02 14:03 UTC, braughtg commented on components/PicklistBase/PicklistBase.vue
> +     * The Map can be empty if no rows are picked.
`The Map will be empty if no rows are picked.`

2024-10-02 14:03 UTC, braughtg commented on modules/farm_fd2_examples/src/entrypoints/picklist_base/App.vue
> +    v-bind:invalidFeedbackText="'At least one row must be selected.'"
Not sure I understand this change...  Is the `v-bind` necessary when the value is a constant?

2024-10-03 01:52 UTC, Shahir-47 commented
@braughtg This PR is ready for review

2024-10-04 17:12 UTC, merged

2024-10-04 17:12 UTC, braughtg commented
Well done!