Update pre-commit to include git hook restage and .only file checks
FarmData2/FarmData2 pull request #67
Opened 2023-11-20 20:37 UTC by WarpWing

**Pull Request Description**

This PR aims to fix #19 , #32 and #33 by implementing checks for `.only` files, readding staged files and reduce redundant `.vue` test runs.

_Include a "Closes #" line for the issue your PR closes._

---

**Licensing Certification**

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request **I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)** for its contents.

2023-11-21 20:14 UTC, braughtg commented
I'll have a look at this tomorrow.  In the meantime, you should be sure to run it through the linters, etc, if you hadn't already.  Two ways to do that:
- manually: `npm run lint`
  - Will lint/format check the entire project.
- via git-hook: 
  - change into `.git`
  - delete the `hooks` directory, 
  - make a symbolic link named `hooks` to `../.githooks`
  - then the files in any commit will be linted/styled/tested before being committed.

2023-11-25 16:44 UTC, braughtg commented
To review:

- Pull the PR.

For #19:
- [ ] - Modify a test file to add `.only` to one test, stage and commit.  Commit should be rejected because of `.only` in the test file.
- [ ] - Modify several test files to contain `.only` tests.  Ensure at least one file has multiple `.only`. Stage and commit. Ensure that commit is rejected until all `.only` are removed.

For #32:
- [ ] - Make change to a file will cause the commit to be rejected.  
- [ ] - Fix the file and save, but don't stage, and attempt commit again.
- [ ] - Should be prompted to restage file.
- [ ] - Respond no to restage and ensure that commit fails again.
- [ ] - Respond yes and ensure that commit is accepted.
- [ ] - Repeat with multiple files.  
  - [ ] - Try restaging some but not all and ensure commit fails.
  - [ ] - Try restaging all and ensure that commit passes.

For #33:
- [ ] - Modify a `.vue` file. Stage and commit.  Ensure all  `.cy.js` tests in directory with the `.vue` still run.
- [ ] - Modify a `.cy.js` file associated with a `.vue` file. Stage and commit. Ensure that the changed `cy.js` tests run.
- [ ] - Modify a `.vue` file and an associated `.cy.js` file.  Stage and commit. 
  - [ ] - Ensure all  `.cy.js` tests in directory with the `.vue` still run.
  - [ ] - Ensure that the modified `cy.js` files are not run a second time.
- [ ] - Modify multiple `.vue` and multiple `.cy.js` associated with each.
  - [ ] - Ensure all `.cy.js` tests in the directory with the `.vue` files run.
  - [ ] - Ensure that the modified `cy.js` files are not run a second time.

2023-11-26 18:26 UTC, braughtg requested changes
The approaches to restaging of files and to not rerunning tests look good (though I have not fully tested them yet).  

For preventing `.only` tests from being commited, I think it would be preferable to use an eslint rule rather than custom scripting.  By adding the lint rule devs will be able to see the warning in VSCode and when running linting before seeing it in the pre-commit hook.  Also in the pre-commit hook the same check will be run just as a regular part of the linting done by `check:staged` - so no modifications to the pre-commit hook will be needed for this part once the rule is added.

Maybe give this plugin a try and see how it does:
- eslint-plugin-no-only-tests: https://www.npmjs.com/package/eslint-plugin-no-only-tests

2023-11-26 18:26 UTC, braughtg commented on .githooks/pre-commit
> +  echo "Instead, create a feature branch and commit your changes to it."
"Instead, create a feature branch from the development branch and commit your changes to it."

2023-11-26 18:26 UTC, braughtg commented on .githooks/pre-commit
> +    read -p "Would you like to restage it? [Y/n]: " -n 1 -r
"Would you like to restage it before committing?"

2023-11-26 18:26 UTC, braughtg commented on .githooks/pre-commit
> +# Check for .only in .cy.js files and mark .vue file tests
See my comment in the overall review comment about possibly using an eslint rule for this instead.

2023-12-01 22:08 UTC, braughtg commented
My PR #79 made some changes to the `lintstagedrc.cjs` file that may need to be considered in continued work on this PR.

2024-01-18 22:34 UTC, WarpWing commented
I'll circle back to this but since there are some merge conflicts, I'm going to delete this and patch my changes back.

2024-01-18 22:34 UTC, closed without merging